name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
    - 
        name: Check out the repo
        uses: actions/checkout@v2
    -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
            version: latest
    -
        name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
        -
            name: Available platforms
            run: echo ${{ steps.buildx.outputs.platforms }}
    - 
        name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: olvesh/my-toolbox
            tag_with_ref: true